export { default as Landing } from "./Landing"
export { default as Footer } from "./Footer"
export { default as Projects } from "./Projects"
export { default as SingleProject } from "./SingleProject"
export { default as Header } from "./Header"
